---
title: "p8105_hw6"
author: "Yiying Chen yc4776"
date: "2025-12-02"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r problem_1_data_clean, warning = FALSE, message = FALSE}
library(tidyverse)
homicide_data = read.csv("data/homicide-data.csv")

homicide_data_clean = homicide_data |>
  mutate(city_state = paste(city, state, sep = ", "),
         resolved = case_when(
      disposition == "Open/No arrest"  ~ 0,
      disposition != "Open/No arrest" ~ 1),
      victim_age = as.numeric(victim_age)) |>
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))|>
  filter(victim_race %in% c("White","Black"))
```

```{r problem_1_Baltimore}
library(broom)

baltimore_data = 
  homicide_data_clean |>
  filter(city_state == "Baltimore, MD")

set.seed(123)
baltimore_fit = 
  baltimore_data |> 
  glm(resolved ~ victim_age + victim_race + victim_sex, data = _, family = binomial()) 

baltimore_fit |> 
  broom::tidy(exponentiate = TRUE, conf.int = TRUE) |> 
  filter(term == "victim_sexMale") |> 
  select(term, OR = estimate, conf.low, conf.high) |> 
  knitr::kable(digits = 3)



```

```{r problem_1_city, warning = FALSE}
city_data =
  homicide_data_clean |>
  group_by(city_state) |>
  tidyr::nest() |>
  mutate(
    city_fit = purrr::map(
      data,
      ~ glm(
          resolved ~ victim_age + victim_sex + victim_race,
          data   = .x,
          family = binomial()
        )
    ),
    city_tidy = purrr::map(
      city_fit,
      ~ broom::tidy(.x, exponentiate = TRUE, conf.int = TRUE)
    )
  ) |>
  tidyr::unnest(city_tidy) |>
  ungroup() |>
  
  filter(term == "victim_sexMale") |>
  select(city_state, estimate, conf.low, conf.high)

city_data
```
```{r problem_1_plot, warning = FALSE, message = FALSE}
city_data |>
  mutate(
    city_state = fct_reorder(city_state, estimate)
  ) |>
  ggplot(aes(x = estimate, y = city_state)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0) +
  labs(
    x = "estimated ORs",
    y = "City",
    title = "Estimated ORs and CIs for each city for solving homicides comparing male victims to female victims"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 6),
    plot.title = element_text(size = 8)
  )
```

```{r problem_2}
library(tidyverse)
library(p8105.datasets)
data("weather_df")

set.seed(123)
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}

boot_straps = 
  tibble(strap_number = 1:5000) |>
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = weather_df))
  )

boot_results =
  boot_straps |> 
  mutate(
    boot_fit   = map(strap_sample,\(df) lm(tmax ~ tmin + prcp, data = df)),
    boot_glance = map(boot_fit, broom::glance),   
    boot_tidy   = map(boot_fit, broom::tidy)
  )

boot_results =
  boot_results |>
  mutate(
    r_squared = map_dbl(boot_glance, "r.squared"),
    beta_ratio = map_dbl(
      boot_tidy,
      \(df) {
        b1 <- filter(df, term == "tmin") |> pull(estimate)
        b2 <- filter(df, term == "prcp") |> pull(estimate)
        b1 / b2
      }
    )
  )|>
  select(strap_number, r_squared, beta_ratio)

ggplot(boot_results, aes(x = r_squared)) +
  geom_histogram(bins = 30, color = "white") +
  labs(
    x = expression(R^2),
    title = "Bootstrap distribution of R-squared"
  ) +
  theme_minimal()

ggplot(boot_results, aes(x = beta_ratio)) +
  geom_histogram(bins = 30, color = "white") +
  labs(
    x = expression(hat(beta)[1] / hat(beta)[2]),
    title = "Bootstrap distribution of beta1/beta2"
  ) +
  theme_minimal()

boot_results |> 
  summarize(
    r2_lower = quantile(r_squared, 0.025),
    r2_upper = quantile(r_squared, 0.975),
    
    ratio_lower = quantile(beta_ratio, 0.025),
    ratio_upper = quantile(beta_ratio, 0.975)
  )
```

#In the Bootstrap distribution of R-squared, it's a nearly symmetric distribution, centered around about 0.94.
#In the Bootstrap distribution of beta1/beta2, it's a right-skewed distribution.